Repository LikeLion13-Central-Team1/BackEnd, pull requests merged in 2025-08, with the labels that each got.

#2 ✨feat: Entity 코드 작성
  src/main/java/com/study/demo/backend/BackEndApplication.java
  src/main/java/com/study/demo/backend/domain/cart/entity/Cart.java
  src/main/java/com/study/demo/backend/domain/cart/entity/CartMenu.java
  src/main/java/com/study/demo/backend/domain/menu/entity/Menu.java
  src/main/java/com/study/demo/backend/domain/order/entity/Order.java
  src/main/java/com/study/demo/backend/domain/order/entity/OrderMenu.java
  src/main/java/com/study/demo/backend/domain/review/entity/Review.java
  src/main/java/com/study/demo/backend/domain/store/entity/Store.java
  src/main/java/com/study/demo/backend/domain/user/entity/User.java
  src/main/java/com/study/demo/backend/domain/user/entity/UserLocation.java
  src/main/java/com/study/demo/backend/domain/user/entity/enums/Role.java
  src/main/java/com/study/demo/backend/global/entity/BaseEntity.java
Labels: ✨feature

#4 ✨ feat: JWT 인증, 로그인, 로그아웃 개발
  build.gradle
  src/main/java/com/study/demo/backend/domain/auth/dto/request/AuthReqDTO.java
  src/main/java/com/study/demo/backend/domain/auth/service/command/JwtTokenCommandService.java
  src/main/java/com/study/demo/backend/domain/auth/service/command/TokenCommandService.java
  src/main/java/com/study/demo/backend/domain/auth/service/query/JwtTokenQueryService.java
  src/main/java/com/study/demo/backend/domain/auth/service/query/TokenQueryService.java
  src/main/java/com/study/demo/backend/domain/user/repository/UserRepository.java
  src/main/java/com/study/demo/backend/global/config/CorsConfig.java
  src/main/java/com/study/demo/backend/global/config/RedisConfig.java
  src/main/java/com/study/demo/backend/global/config/SecurityConfig.java
  src/main/java/com/study/demo/backend/global/config/SwaggerConfig.java
  src/main/java/com/study/demo/backend/global/security/annotation/CurrentUser.java
  src/main/java/com/study/demo/backend/global/security/dto/JwtDTO.java
  src/main/java/com/study/demo/backend/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/study/demo/backend/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/study/demo/backend/global/security/exception/SecurityErrorCode.java
  src/main/java/com/study/demo/backend/global/security/filter/CustomLoginFilter.java
  src/main/java/com/study/demo/backend/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/study/demo/backend/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/study/demo/backend/global/security/userdetails/AuthUser.java
  src/main/java/com/study/demo/backend/global/security/userdetails/CustomUserDetails.java
  src/main/java/com/study/demo/backend/global/security/userdetails/CustomUserDetailsService.java
  src/main/java/com/study/demo/backend/global/security/utils/JwtUtil.java
  src/main/java/com/study/demo/backend/global/utils/HttpResponseUtil.java
  src/main/java/com/study/demo/backend/global/utils/RedisUtil.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
Labels: ✨feature

#11 ✨ feat: Store 등록, 조회, 수정 API 개발
  src/main/java/com/study/demo/backend/domain/store/controller/StoreController.java
  src/main/java/com/study/demo/backend/domain/store/converter/StoreConverter.java
  src/main/java/com/study/demo/backend/domain/store/dto/request/StoreReqDTO.java
  src/main/java/com/study/demo/backend/domain/store/dto/response/StoreResDTO.java
  src/main/java/com/study/demo/backend/domain/store/entity/Store.java
  src/main/java/com/study/demo/backend/domain/store/entity/enums/StoreSortType.java
  src/main/java/com/study/demo/backend/domain/store/exception/StoreErrorCode.java
  src/main/java/com/study/demo/backend/domain/store/exception/StoreException.java
  src/main/java/com/study/demo/backend/domain/store/repository/StoreRepository.java
  src/main/java/com/study/demo/backend/domain/store/service/command/CommandService.java
  src/main/java/com/study/demo/backend/domain/store/service/command/CommandServiceImpl.java
  src/main/java/com/study/demo/backend/domain/store/service/query/QueryService.java
  src/main/java/com/study/demo/backend/domain/store/service/query/QueryServiceImpl.java
Labels: ✨feature

#14 ✨feat: 장바구니 API 개발
  src/main/java/com/study/demo/backend/domain/cart/controller/CartController.java
  src/main/java/com/study/demo/backend/domain/cart/converter/CartConverter.java
  src/main/java/com/study/demo/backend/domain/cart/dto/requset/CartReqDTO.java
  src/main/java/com/study/demo/backend/domain/cart/dto/response/CartResDTO.java
  src/main/java/com/study/demo/backend/domain/cart/entity/CartMenu.java
  src/main/java/com/study/demo/backend/domain/cart/exception/CartErrorCode.java
  src/main/java/com/study/demo/backend/domain/cart/exception/CartException.java
  src/main/java/com/study/demo/backend/domain/cart/repository/CartMenuRepository.java
  src/main/java/com/study/demo/backend/domain/cart/repository/CartRepository.java
  src/main/java/com/study/demo/backend/domain/cart/service/command/CartCommandService.java
  src/main/java/com/study/demo/backend/domain/cart/service/command/CartCommandServiceImpl.java
  src/main/java/com/study/demo/backend/domain/cart/service/query/CartQueryService.java
  src/main/java/com/study/demo/backend/domain/cart/service/query/CartQueryServiceImpl.java
  src/main/java/com/study/demo/backend/domain/menu/repository/MenuRepository.java
  src/main/java/com/study/demo/backend/domain/review/controller/ReviewController.java
  src/main/java/com/study/demo/backend/global/apiPayload/CustomResponse.java
Labels: ✨feature

#18 ✨ feat: Menu 등록, 조회, 수정, 삭제 API 개발
  .gitignore
  src/main/java/com/study/demo/backend/domain/menu/controller/MenuController.java
  src/main/java/com/study/demo/backend/domain/menu/converter/MenuConverter.java
  src/main/java/com/study/demo/backend/domain/menu/dto/request/MenuReqDTO.java
  src/main/java/com/study/demo/backend/domain/menu/dto/response/MenuResDTO.java
  src/main/java/com/study/demo/backend/domain/menu/entity/Menu.java
  src/main/java/com/study/demo/backend/domain/menu/entity/menuEnums/MenuSortType.java
  src/main/java/com/study/demo/backend/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/study/demo/backend/domain/menu/exception/MenuException.java
  src/main/java/com/study/demo/backend/domain/menu/repository/MenuRepository.java
  src/main/java/com/study/demo/backend/domain/menu/service/command/MenuCommandService.java
  src/main/java/com/study/demo/backend/domain/menu/service/command/MenuCommandServiceImpl.java
  src/main/java/com/study/demo/backend/domain/menu/service/query/MenuQueryService.java
  src/main/java/com/study/demo/backend/domain/menu/service/query/MenuQueryServiceImpl.java
  src/main/java/com/study/demo/backend/domain/store/controller/StoreController.java
  src/main/java/com/study/demo/backend/domain/store/entity/storeEnums/StoreSortType.java
  src/main/java/com/study/demo/backend/domain/store/service/command/StoreCommandService.java
  src/main/java/com/study/demo/backend/domain/store/service/command/StoreCommandServiceImpl.java
  src/main/java/com/study/demo/backend/domain/store/service/query/StoreQueryService.java
  src/main/java/com/study/demo/backend/domain/store/service/query/StoreQueryServiceImpl.java
  src/main/java/com/study/demo/backend/global/ImgUploader/FileUploader.java
  src/main/java/com/study/demo/backend/global/ImgUploader/LocalUploader.java
  src/main/java/com/study/demo/backend/global/config/SecurityConfig.java
  src/main/java/com/study/demo/backend/global/config/StaticResourceConfig.java
  src/main/resources/application-local.yml
  uploads/menu/2d8c72ed-6411-450e-9628-4e687b208765.png
  uploads/menu/6d7e5500-bf56-459c-ad72-9fbd57eb60f0.png
  uploads/menu/90249154-880c-4af8-943d-f2771b585cdd.jpg
  uploads/menu/c667ccb2-a1d0-4a45-bcf7-237381d8b1fa.png
Labels: ✨feature

#24 ✨ feat: Menu AI 설명 기능 추가 & Menu 삭제 리펙토링
  src/main/java/com/study/demo/backend/domain/menu/controller/MenuController.java
  src/main/java/com/study/demo/backend/domain/menu/dto/request/MenuReqDTO.java
  src/main/java/com/study/demo/backend/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/study/demo/backend/domain/menu/service/command/GPTImgService.java
  src/main/java/com/study/demo/backend/domain/menu/service/command/GPTImgServiceImpl.java
  src/main/java/com/study/demo/backend/global/ImgUploader/LocalUploader.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
Labels: ♻️refactor, ✨feature

#26 ✨ feat: Order API 개발
  src/main/java/com/study/demo/backend/domain/menu/controller/MenuController.java
  src/main/java/com/study/demo/backend/domain/order/controller/OrderController.java
  src/main/java/com/study/demo/backend/domain/order/converter/OrderConverter.java
  src/main/java/com/study/demo/backend/domain/order/dto/request/OrderReqDTO.java
  src/main/java/com/study/demo/backend/domain/order/dto/response/OrderResDTO.java
  src/main/java/com/study/demo/backend/domain/order/entity/Order.java
  src/main/java/com/study/demo/backend/domain/order/entity/OrderMenu.java
  src/main/java/com/study/demo/backend/domain/order/exception/OrderErrorCode.java
  src/main/java/com/study/demo/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/study/demo/backend/domain/order/service/command/OrderCommandService.java
  src/main/java/com/study/demo/backend/domain/order/service/command/OrderCommandServiceImpl.java
  src/main/java/com/study/demo/backend/domain/order/service/query/OrderQueryService.java
  src/main/java/com/study/demo/backend/domain/order/service/query/OrderQueryServiceImpl.java
Labels: ✨feature

#28 ♻️refactor: 가게, 위치 Response 수정
  src/main/java/com/study/demo/backend/domain/store/converter/StoreConverter.java
  src/main/java/com/study/demo/backend/domain/store/dto/response/StoreResDTO.java
  src/main/java/com/study/demo/backend/domain/store/entity/Store.java
  src/main/java/com/study/demo/backend/domain/user/converter/UserLocationConverter.java
  src/main/java/com/study/demo/backend/domain/user/dto/request/UserLocationReqDTO.java
  src/main/java/com/study/demo/backend/domain/user/dto/response/UserLocationResDTO.java
  src/main/java/com/study/demo/backend/domain/user/entity/UserLocation.java
Labels: ♻️refactor

#30 ♻️refactor: GPT 리뷰 요약에 Redis 캐시 적용
  src/main/java/com/study/demo/backend/domain/review/service/command/GPTServiceImpl.java
  src/main/java/com/study/demo/backend/domain/review/service/query/ReviewQueryServiceImpl.java
  src/main/java/com/study/demo/backend/global/config/RedisConfig.java
Labels: ♻️refactor

#36 ♻️ refactor: 메뉴 조회시 응답 DTO 수정하기
  src/main/java/com/study/demo/backend/domain/menu/converter/MenuConverter.java
  src/main/java/com/study/demo/backend/domain/menu/dto/request/MenuReqDTO.java
  src/main/java/com/study/demo/backend/domain/menu/dto/response/MenuResDTO.java
  src/main/java/com/study/demo/backend/domain/menu/repository/MenuRepository.java
  src/main/java/com/study/demo/backend/domain/menu/service/command/GPTImgServiceImpl.java
  src/main/java/com/study/demo/backend/domain/menu/service/query/MenuQueryServiceImpl.java
Labels: ♻️refactor

#42 ✨ feat: Store와 Order 관련 기능 개발 및 수정
  src/main/java/com/study/demo/backend/domain/order/controller/OrderController.java
  src/main/java/com/study/demo/backend/domain/order/exception/OrderErrorCode.java
  src/main/java/com/study/demo/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/study/demo/backend/domain/order/service/command/OrderCommandServiceImpl.java
  src/main/java/com/study/demo/backend/domain/order/service/query/OrderQueryService.java
  src/main/java/com/study/demo/backend/domain/order/service/query/OrderQueryServiceImpl.java
  src/main/java/com/study/demo/backend/domain/store/controller/StoreController.java
  src/main/java/com/study/demo/backend/domain/store/converter/StoreConverter.java
  src/main/java/com/study/demo/backend/domain/store/dto/request/StoreReqDTO.java
  src/main/java/com/study/demo/backend/domain/store/dto/response/StoreResDTO.java
  src/main/java/com/study/demo/backend/domain/store/entity/Store.java
  src/main/java/com/study/demo/backend/domain/store/exception/StoreErrorCode.java
  src/main/java/com/study/demo/backend/domain/store/repository/StoreRepository.java
  src/main/java/com/study/demo/backend/domain/store/service/command/StoreCommandService.java
  src/main/java/com/study/demo/backend/domain/store/service/command/StoreCommandServiceImpl.java
Labels: ✨feature

#50 ♻️ refactor: 이미지 저장 경로 수정
  src/main/java/com/study/demo/backend/global/ImgUploader/LocalUploader.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
Labels: ♻️refactor

#52 ♻️ refactor: 가게 상태 필드 추가 & 스케줄러 기능 추가
  src/main/java/com/study/demo/backend/domain/store/controller/StoreController.java
  src/main/java/com/study/demo/backend/domain/store/converter/StoreConverter.java
  src/main/java/com/study/demo/backend/domain/store/dto/response/StoreResDTO.java
  src/main/java/com/study/demo/backend/domain/store/entity/Store.java
  src/main/java/com/study/demo/backend/domain/store/exception/StoreErrorCode.java
  src/main/java/com/study/demo/backend/domain/store/service/command/StoreCommandServiceImpl.java
  src/main/java/com/study/demo/backend/global/scheduler/StockResetScheduler.java
Labels: ♻️refactor

#54 ✨ feat: 프런트 연습용 배포 cors에 추가하기
  src/main/java/com/study/demo/backend/global/config/CorsConfig.java
Labels: ✨feature
